import { useEffect, useState } from "react";
import { collection, onSnapshot, query, orderBy, limit } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { db, functions } from "../lib/firebase";
import { DollarSign, PlusCircle, MinusCircle, Store as StoreIcon, TrendingUp, Search, ArrowDownCircle, ArrowUpCircle, Wallet, Clock3, CheckCircle2, XCircle } from "lucide-react";
import { Card, Button, Input, EmptyState, useToast } from "@vaptvupt/shared-ui";
interface StoreDoc{id:string;name:string;balance:number}
interface Transaction{id:string;storeId:string;type:string;amount:number;description:string;createdAt:any}
interface PixRequest{id:string;storeId:string;storeName:string;amount:number;status:string;createdAt:any;payerName?:string;paymentReference?:string}
const money=(v:number)=>`R$ ${Number(v||0).toFixed(2).replace(".",",")}`;
export default function Finance(){
 const {toast}=useToast();const[stores,setStores]=useState<StoreDoc[]>([]),[transactions,setTransactions]=useState<Transaction[]>([]),[requests,setRequests]=useState<PixRequest[]>([]);
 const[selectedStore,setSelectedStore]=useState<StoreDoc|null>(null),[searchStore,setSearchStore]=useState(""),[amount,setAmount]=useState(0),[description,setDescription]=useState(""),[operation,setOperation]=useState<"credit"|"debit">("credit"),[processing,setProcessing]=useState(false),[processingPix,setProcessingPix]=useState<string|null>(null);
 useEffect(()=>onSnapshot(collection(db,"stores"),s=>setStores(s.docs.map(d=>({id:d.id,name:d.data().name||"Sem nome",balance:Number(d.data().balance||0)}))),[]);
 useEffect(()=>{const q=query(collection(db,"transactions"),orderBy("createdAt","desc"),limit(30));return onSnapshot(q,s=>setTransactions(s.docs.map(d=>({id:d.id,...d.data()} as Transaction))));},[]);
 useEffect(()=>{const q=query(collection(db,"pixTopupRequests"),orderBy("createdAt","desc"),limit(50));return onSnapshot(q,s=>setRequests(s.docs.map(d=>({id:d.id,...d.data()} as PixRequest))));},[]);
 const filtered=stores.filter(s=>s.name.toLowerCase().includes(searchStore.toLowerCase())),pending=requests.filter(r=>r.status==="PENDING"),totalBalance=stores.reduce((s,x)=>s+x.balance,0);
 const processPix=async(id:string,approve:boolean)=>{setProcessingPix(id);try{const fn=httpsCallable(functions,approve?"approvePixTopupRequest":"rejectPixTopupRequest");await fn(approve?{requestId:id}:{requestId:id,reason:"Pagamento não localizado ou não confirmado."});toast(approve?"Recarga aprovada e saldo liberado!":"Solicitação recusada.","success");}catch(e:any){toast(e?.message||"Não foi possível processar.","error");}finally{setProcessingPix(null);}};
 const handleSubmit=async()=>{if(!selectedStore||amount<=0){toast("Selecione uma loja e informe um valor maior que zero","error");return;}setProcessing(true);try{const fn=httpsCallable(functions,"adminAdjustStoreBalance");await fn({storeId:selectedStore.id,amount:operation==="credit"?amount:-amount,description:description||(operation==="credit"?"Crédito manual":"Débito manual")});toast("Ajuste financeiro aplicado!","success");setAmount(0);setDescription("");setSelectedStore(null);setSearchStore("");}catch(e:any){toast(e?.message||"Falha no ajuste.","error");}finally{setProcessing(false);}};
 return <div className="p-4 sm:p-6 lg:p-8"><div className="mb-8"><h1 className="text-3xl font-bold text-slate-800">Financeiro Global</h1><p className="text-slate-500 mt-1">Saldo das lojas, recargas PIX e extrato</p></div>
 <div className="grid grid-cols-1 md:grid-cols-4 gap-5 mb-8"><Kpi icon={<Wallet size={22}/>} label="Total em Carteiras" value={money(totalBalance)}/><Kpi icon={<StoreIcon size={22}/>} label="Lojas Ativas" value={stores.length}/><Kpi icon={<Clock3 size={22}/>} label="PIX pendentes" value={pending.length}/><Kpi icon={<TrendingUp size={22}/>} label="Transações" value={transactions.length}/></div>
 <Card className="mb-6"><div className="flex items-center justify-between mb-4"><div><h2 className="text-lg font-bold">Recargas PIX aguardando conferência</h2><p className="text-xs text-slate-500 mt-1">Confira o pagamento na sua conta antes de aprovar.</p></div><span className="bg-amber-100 text-amber-800 px-3 py-1 rounded-full text-xs font-bold">{pending.length} pendente(s)</span></div>{pending.length===0?<p className="text-sm text-slate-500">Nenhuma recarga aguardando conferência.</p>:<div className="space-y-3">{pending.map(r=><div key={r.id} className="border border-slate-200 rounded-xl p-4"><div className="flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><div className="flex items-center gap-2"><p className="font-bold">{r.storeName}</p><span className="text-xs text-slate-400">#{r.id.slice(0,8)}</span></div><p className="text-xl font-bold text-emerald-600 mt-1">{money(r.amount)}</p><div className="text-xs text-slate-500 mt-2 space-y-1"><p>Pagador: {r.payerName||"Não informado"}</p><p>Referência: {r.paymentReference||"Não informada"}</p></div></div><div className="flex gap-2"><Button variant="success" loading={processingPix===r.id} icon={<CheckCircle2 size={17}/>} onClick={()=>processPix(r.id,true)}>Confirmar pagamento</Button><Button variant="danger" disabled={processingPix===r.id} icon={<XCircle size={17}/>} onClick={()=>processPix(r.id,false)}>Recusar</Button></div></div></div>)}</div>}</Card>
 <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><h2 className="text-lg font-bold text-slate-800 mb-5">Ajuste Manual</h2><div className="flex gap-2 mb-5"><button onClick={()=>setOperation("credit")} className={`flex-1 py-2.5 rounded-lg font-semibold ${operation==="credit"?"bg-emerald-600 text-white":"bg-slate-100 text-slate-600"}`}><PlusCircle size={18} className="inline mr-2"/>Creditar</button><button onClick={()=>setOperation("debit")} className={`flex-1 py-2.5 rounded-lg font-semibold ${operation==="debit"?"bg-red-600 text-white":"bg-slate-100 text-slate-600"}`}><MinusCircle size={18} className="inline mr-2"/>Debitar</button></div><label className="block text-sm font-semibold text-slate-700 mb-1.5">Buscar loja</label><Input placeholder="Digite o nome da loja..." value={searchStore} onChange={e=>setSearchStore(e.target.value)} icon={<Search size={16}/>}/>{searchStore&&filtered.length>0&&!selectedStore&&<div className="mt-2 max-h-40 overflow-auto border rounded-lg bg-white">{filtered.map(s=><button key={s.id} onClick={()=>{setSelectedStore(s);setSearchStore(s.name)}} className="w-full text-left px-4 py-2.5 hover:bg-emerald-50 text-sm border-b"><span className="font-medium">{s.name}</span><span className="float-right text-emerald-600 font-semibold">{money(s.balance)}</span></button>)}</div>}{selectedStore&&<div className="mt-2 bg-emerald-50 border border-emerald-200 rounded-lg p-3 flex justify-between"><div><p className="text-sm font-semibold text-emerald-900">{selectedStore.name}</p><p className="text-xs text-emerald-700">Saldo: {money(selectedStore.balance)}</p></div><button onClick={()=>{setSelectedStore(null);setSearchStore("")}} className="text-emerald-600 text-sm">Trocar</button></div>}<div className="mt-4"><Input label="Valor (R$)" type="number" step="0.01" value={amount||""} onChange={e=>setAmount(Number(e.target.value)||0)} placeholder="0,00"/></div><div className="mt-4 mb-5"><Input label="Descrição" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex: Estorno"/></div><Button variant={operation==="credit"?"success":"danger"} fullWidth size="lg" loading={processing} onClick={handleSubmit}>{operation==="credit"?"Creditar":"Debitar"} {money(amount)}</Button></Card>
 <Card padded={false}><div className="p-5 border-b"><h2 className="font-bold">Últimas Transações</h2></div><div className="max-h-[600px] overflow-auto">{transactions.length===0?<EmptyState icon={<DollarSign size={32}/>} title="Nenhuma transação" description="As movimentações aparecerão aqui."/>:<div className="divide-y divide-slate-100">{transactions.map(t=>{const credit=t.amount>0;return <div key={t.id} className="p-4 flex items-center gap-3"><div className={`p-2 rounded-lg ${credit?"bg-emerald-100 text-emerald-600":"bg-red-100 text-red-600"}`}>{credit?<ArrowUpCircle size={18}/>:<ArrowDownCircle size={18}/>}</div><div className="flex-1 min-w-0"><p className="text-sm font-semibold truncate">{stores.find(s=>s.id===t.storeId)?.name||"Loja removida"}</p><p className="text-xs text-slate-500 truncate">{t.description}</p></div><span className={`font-bold text-sm ${credit?"text-emerald-600":"text-red-600"}`}>{credit?"+":"-"} {money(Math.abs(t.amount))}</span></div>})}</div>}</div></Card></div>
 </div>;
}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="bg-white rounded-2xl border border-slate-200 p-5 flex items-center gap-4"><div className="p-3 rounded-xl bg-slate-100">{icon}</div><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></div></div>}
