import {useEffect,useMemo,useState} from "react";
import {collection,onSnapshot,orderBy,query} from "firebase/firestore";
import {db} from "../lib/firebase";
import {Clock,Package,Search,ChevronRight} from "lucide-react";
const terminal=["DELIVERED","CANCELLED","FAILED"];
const labels:Record<string,string>={PENDING:"Pendente",SEARCHING_DRIVER:"Buscando entregador",OFFERED:"Oferta enviada",ACCEPTED:"Aceito",ARRIVING_PICKUP:"A caminho da coleta",COLLECTED:"Coletado",IN_DELIVERY:"Em entrega",ARRIVING_DESTINATION:"Chegando",DELIVERED:"Entregue",CANCELLED:"Cancelado",FAILED:"Falhou"};
const badge=(s:string)=>s==="DELIVERED"?"bg-emerald-100 text-emerald-700":terminal.includes(s)?"bg-red-100 text-red-700":["SEARCHING_DRIVER","OFFERED"].includes(s)?"bg-amber-100 text-amber-700":"bg-blue-100 text-blue-700";
export default function Orders(){const [orders,setOrders]=useState<any[]>([]),[status,setStatus]=useState("ALL"),[search,setSearch]=useState(""),[selected,setSelected]=useState<any>(null);
useEffect(()=>onSnapshot(query(collection(db,"orders"),orderBy("createdAt","desc")),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
const filtered=useMemo(()=>orders.filter(o=>(status==="ALL"||o.status===status)&&( !search||o.id.toLowerCase().includes(search.toLowerCase())||(o.storeName||"").toLowerCase().includes(search.toLowerCase()) )),[orders,status,search]);
return <div className="p-4 sm:p-6 lg:p-8 max-w-[1500px] mx-auto"><div className="mb-6"><p className="text-sm font-semibold text-blue-600">Operação</p><h1 className="text-3xl font-bold text-slate-900">Pedidos</h1><p className="text-slate-500 mt-1">Central operacional com histórico e status.</p></div>
<div className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-4 border-b border-slate-200 flex flex-col lg:flex-row gap-3"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por pedido ou loja" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-slate-200 text-sm"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="px-3 py-2.5 rounded-xl border border-slate-200 text-sm"><option value="ALL">Todos os status</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
<div className="divide-y divide-slate-100">{filtered.map(o=><button key={o.id} onClick={()=>setSelected(o)} className="w-full text-left p-4 hover:bg-slate-50 flex items-center gap-4"><div className="p-3 bg-slate-100 rounded-xl"><Package size={19}/></div><div className="flex-1 min-w-0"><p className="font-semibold text-sm text-slate-900">#{o.id.slice(0,10)} · {o.storeName||"Loja"}</p><p className="text-xs text-slate-500 mt-1">{o.pricing?.distanceKm?.toFixed?.(1)||"—"} km · {o.assignedDriverId?"Entregador atribuído":"Sem entregador"}</p></div><span className={`text-[11px] font-semibold px-2.5 py-1 rounded-full ${badge(o.status)}`}>{labels[o.status]||o.status}</span><ChevronRight size={18} className="text-slate-400"/></button>)}{filtered.length===0&&<div className="p-12 text-center text-sm text-slate-500">Nenhum pedido encontrado.</div>}</div></div>
{selected&&<div className="fixed inset-0 z-50 bg-black/40 flex justify-end" onClick={()=>setSelected(null)}><div className="w-full max-w-xl bg-white h-full overflow-y-auto p-6" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs text-blue-600 font-semibold">PEDIDO</p><h2 className="text-2xl font-bold mt-1">#{selected.id.slice(0,10)}</h2><p className="text-sm text-slate-500">{selected.storeName||"Loja"}</p></div><button onClick={()=>setSelected(null)} className="text-slate-400 text-2xl">×</button></div><div className="mt-6 p-4 bg-slate-50 rounded-xl"><p className="font-semibold text-sm">Status atual</p><span className={`inline-block mt-2 text-xs font-semibold px-2.5 py-1 rounded-full ${badge(selected.status)}`}>{labels[selected.status]||selected.status}</span></div><h3 className="font-bold mt-6 mb-3">Timeline</h3><div className="space-y-3">{(selected.statusHistory||[]).map((h:any,i:number)=><div key={i} className="flex gap-3"><div className="w-2 h-2 rounded-full bg-blue-600 mt-2"/><div><p className="text-sm font-semibold">{labels[h.status]||h.status}</p><p className="text-xs text-slate-500">{h.at?.toDate?.()?.toLocaleString?.("pt-BR")||"Registro do sistema"}</p></div></div>)}{!(selected.statusHistory||[]).length&&<p className="text-sm text-slate-500">O histórico deste pedido ainda não está disponível.</p>}</div><div className="grid grid-cols-2 gap-3 mt-7"><Info label="Entregador" value={selected.assignedDriverId||"Aguardando"}/><Info label="Frete" value={`R$ ${(selected.pricing?.totalFee||0).toFixed(2)}`}/><Info label="Distância" value={`${selected.pricing?.distanceKm?.toFixed?.(1)||"—"} km`}/><Info label="Paradas" value={String(selected.stops?.length||0)}/></div></div></div>}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="border border-slate-200 rounded-xl p-3"><p className="text-[11px] text-slate-500">{label}</p><p className="font-semibold text-sm mt-1 truncate">{value}</p></div>}