import { useEffect, useState } from "react";
import { collection, onSnapshot, query, where, orderBy } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { db, functions } from "../lib/firebase";
import { useStore } from "../context/StoreContext";
import { Wallet as WalletIcon, Plus, ArrowDownCircle, ArrowUpCircle, Copy, CheckCircle2, TrendingUp, TrendingDown, Clock3, Send } from "lucide-react";
import { Button, Card, Modal, EmptyState, useToast } from "@vaptvupt/shared-ui";
interface Transaction { id:string; type:string; amount:number; description:string; createdAt:any; }
interface PixRequest { id:string; amount:number; status:string; createdAt:any; paymentReference?:string; rejectionReason?:string; }
const money=(v:number)=>`R$ ${Number(v||0).toFixed(2).replace(".",",")}`;
export default function Wallet(){
 const {store}=useStore(); const {toast}=useToast();
 const [transactions,setTransactions]=useState<Transaction[]>([]),[requests,setRequests]=useState<PixRequest[]>([]);
 const [showPixModal,setShowPixModal]=useState(false),[pixAmount,setPixAmount]=useState(100),[payerName,setPayerName]=useState(""),[paymentReference,setPaymentReference]=useState("");
 const [pixKey,setPixKey]=useState(""),[receiverName,setReceiverName]=useState("VaptVupt"),[copied,setCopied]=useState(false),[sending,setSending]=useState(false);
 useEffect(()=>{if(!store)return;const q=query(collection(db,"transactions"),where("storeId","==",store.id),orderBy("createdAt","desc"));return onSnapshot(q,s=>setTransactions(s.docs.map(d=>({id:d.id,...d.data()} as Transaction))));},[store]);
 useEffect(()=>{if(!store)return;const q=query(collection(db,"pixTopupRequests"),where("storeId","==",store.id),orderBy("createdAt","desc"));return onSnapshot(q,s=>setRequests(s.docs.map(d=>({id:d.id,...d.data()} as PixRequest))));},[store]);
 useEffect(()=>{const load=async()=>{try{const fn=httpsCallable(functions,"getManualPixSettings");const r:any=await fn({});setPixKey(r.data.pixKey);setReceiverName(r.data.receiverName||"VaptVupt");}catch{}};load();},[]);
 const copy=async()=>{if(!pixKey)return;await navigator.clipboard.writeText(pixKey);setCopied(true);toast("Chave PIX copiada!","success");setTimeout(()=>setCopied(false),1800);};
 const submit=async()=>{if(!store||pixAmount<=0){toast("Informe um valor maior que zero.","error");return;}setSending(true);try{await httpsCallable(functions,"createPixTopupRequest")({storeId:store.id,amount:Number(pixAmount),payerName,paymentReference});toast("Solicitação enviada. Aguarde a conferência do pagamento.","success");setShowPixModal(false);setPayerName("");setPaymentReference("");}catch(e:any){toast(e?.message||"Não foi possível solicitar a recarga.","error");}finally{setSending(false);}};
 const totalCredit=transactions.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0),totalDebit=Math.abs(transactions.filter(t=>t.amount<0).reduce((s,t)=>s+t.amount,0));
 return <div className="p-4 sm:p-6 lg:p-8 max-w-6xl mx-auto">
  <div className="mb-8"><h1 className="text-3xl font-bold text-slate-800">Carteira</h1><p className="text-slate-500 mt-1">Saldo, recargas via PIX e extrato</p></div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8"><div className="md:col-span-2 bg-gradient-to-br from-emerald-500 via-emerald-600 to-emerald-800 rounded-2xl p-7 text-white shadow-xl"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2 text-emerald-100"><WalletIcon size={20}/><span className="text-sm">Saldo disponível</span></div><Button variant="secondary" size="sm" icon={<Plus size={16}/>} onClick={()=>setShowPixModal(true)} className="bg-white/20 hover:bg-white/30 text-white border-0">Adicionar saldo</Button></div><p className="text-5xl font-bold mb-2">{money(store?.balance||0)}</p><p className="text-emerald-100 text-sm">{store?.name}</p></div><div className="space-y-4"><Card><p className="text-xs text-slate-500">Total creditado</p><p className="text-lg font-bold text-slate-800">{money(totalCredit)}</p></Card><Card><p className="text-xs text-slate-500">Total em fretes</p><p className="text-lg font-bold text-slate-800">{money(totalDebit)}</p></Card></div></div>
  <Card className="mb-6"><div className="flex items-start gap-4"><div className="bg-amber-100 text-amber-700 p-3 rounded-xl"><Send size={20}/></div><div className="flex-1"><h2 className="font-bold text-slate-800">Recarga via PIX</h2><p className="text-sm text-slate-600 mt-1">Faça o PIX para a chave abaixo e depois envie a solicitação. O saldo só é liberado após conferência manual.</p><div className="mt-4 flex flex-col sm:flex-row gap-3"><div className="flex-1 bg-slate-50 border border-slate-200 rounded-xl p-3"><p className="text-xs text-slate-500">Chave PIX</p><p className="font-bold text-slate-800 mt-1">{pixKey||"Carregando..."}</p><p className="text-xs text-slate-500 mt-1">Recebedor: {receiverName}</p></div><Button variant="secondary" icon={copied?<CheckCircle2 size={17}/>:<Copy size={17}/>} onClick={copy}>{copied?"Copiado":"Copiar chave"}</Button></div></div></div></Card>
  <Card className="mb-6"><h2 className="text-lg font-bold text-slate-800 mb-4">Solicitações de recarga</h2>{requests.length===0?<p className="text-sm text-slate-500">Nenhuma solicitação registrada.</p>:<div className="space-y-2">{requests.slice(0,8).map(r=><div key={r.id} className="border border-slate-200 rounded-xl p-3 flex items-center gap-3"><div className="p-2 rounded-lg bg-slate-100"><Clock3 size={17}/></div><div className="flex-1"><p className="font-semibold">{money(r.amount)}</p><p className="text-xs text-slate-500">{r.paymentReference||"Sem referência"}</p>{r.rejectionReason&&<p className="text-xs text-red-600 mt-1">{r.rejectionReason}</p>}</div><span className={`text-xs font-bold px-2.5 py-1 rounded-full ${r.status==="APPROVED"?"bg-green-100 text-green-700":r.status==="REJECTED"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{r.status==="APPROVED"?"Aprovada":r.status==="REJECTED"?"Recusada":"Aguardando"}</span></div>)}</div>}</Card>
  <Card><h2 className="text-lg font-bold text-slate-800 mb-4">Extrato</h2>{transactions.length===0?<EmptyState icon={<WalletIcon size={32}/>} title="Nenhuma transação ainda" description='Use "Adicionar saldo" para solicitar uma recarga.'/>:<div className="divide-y divide-slate-100 -mx-6">{transactions.map(t=>{const credit=t.amount>0;return <div key={t.id} className="px-6 py-4 flex items-center gap-4"><div className={`p-3 rounded-xl ${credit?"bg-green-100 text-green-600":"bg-red-100 text-red-600"}`}>{credit?<ArrowUpCircle size={20}/>:<ArrowDownCircle size={20}/>}</div><div className="flex-1"><p className="font-semibold text-slate-800">{t.description}</p><p className="text-xs text-slate-500">{t.type==="CREDIT_PIX_MANUAL"?"Recarga PIX manual":t.type==="DEBIT_DELIVERY"?"Frete de entrega":t.type}</p></div><span className={`font-bold ${credit?"text-green-600":"text-red-600"}`}>{credit?"+":"-"} {money(Math.abs(t.amount))}</span></div>})}</div>}</Card>
  <Modal open={showPixModal} onClose={()=>setShowPixModal(false)} title="Adicionar saldo via PIX"><div className="space-y-4"><div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4"><p className="text-xs text-emerald-700 font-semibold">1. Faça o PIX</p><p className="text-lg font-bold text-emerald-900 mt-1">{pixKey||"Carregando..."}</p><p className="text-xs text-emerald-700 mt-1">Recebedor: {receiverName}</p><button onClick={copy} className="mt-3 text-sm font-semibold text-emerald-700">{copied?"Chave copiada!":"Copiar chave PIX"}</button></div><div className="grid grid-cols-2 gap-2">{[50,100,200,500].map(v=><button key={v} onClick={()=>setPixAmount(v)} className={`py-2.5 rounded-lg border-2 font-semibold ${pixAmount===v?"border-emerald-600 bg-emerald-50 text-emerald-700":"border-slate-200 text-slate-600"}`}>R$ {v}</button>)}</div><input type="number" min="0.01" max="100000" step="0.01" value={pixAmount} onChange={e=>setPixAmount(Number(e.target.value)||0)} className="w-full px-4 py-3 border border-slate-300 rounded-lg bg-white text-slate-800" placeholder="Valor pago"/><input value={payerName} onChange={e=>setPayerName(e.target.value)} className="w-full px-4 py-3 border border-slate-300 rounded-lg bg-white text-slate-800" placeholder="Nome de quem fez o PIX (opcional)"/><input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} className="w-full px-4 py-3 border border-slate-300 rounded-lg bg-white text-slate-800" placeholder="ID/referência do comprovante (opcional)"/><p className="text-xs text-slate-500">2. Depois de pagar, envie a solicitação. O administrador conferirá o pagamento antes de liberar o saldo.</p><Button variant="success" fullWidth size="lg" loading={sending} onClick={submit}>Enviar solicitação de recarga</Button></div></Modal>
 </div>;
}
